- Effect: "Allow"
  Action:
    - "s3:*"
  Resource:
    - Fn::GetAtt: [S3BucketMigration,Arn]
    - Fn::Join:
      - "/"
      - - Fn::GetAtt: [S3BucketMigration,Arn]
        - "*"
- Effect: "Allow"
  Action:
    - "s3:PutObject"
  Resource:
    - arn:aws:s3:::*/*
- Effect: "Allow"
  Action:
    - "dynamodb:BatchGetItem"
    - "dynamodb:BatchWriteItem"
    - "dynamodb:PutItem"
    - "dynamodb:GetItem"
    - "dynamodb:Scan"
    - "dynamodb:Query"
    - "dynamodb:UpdateItem"
  Resource: "*"
